import { Poppins, Fira_Sans, Cedarville_Cursive} from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

const poppins = Fira_Sans({ 
  weight: ['400'],
  subsets: ['latin'],
  variable: '--font-poppins',
 })

 const cedarville = Cedarville_Cursive({ 
  weight: ['400'],
  subsets: ['latin'],
  variable: '--font-cedarville',
 })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${cedarville.variable} ${poppins.variable}`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
